export const icons = {
    IC_USER: require('../assets/icons/User.png'),
    IC_PASSWORD:require('../assets/icons/password.png'),
    IC_EMAIL:require('../assets/icons/ic_mail.png'),
    IC_GOOGLE:require('../assets/icons/google1.png'),
    IC_APPLE:require('../assets/icons/apple.png'),
    IC_FACEBOOK:require('../assets/icons/facebook1.png'),
    IC_EYE_OPEN:require('../assets/icons/eye_open1.png'),
    IC_EYE_CLOSE:require('../assets/icons/eye_close1.png'),
    IC_MIC_OFF:require('../assets/icons/mic1.png'),
    IC_MIC_ON:require('../assets/icons/mic2.png'),
    IC_SEARCH: require('../assets/icons/search1.png'),
    IC_BOTTOMMENU_HOMESELECT: require('../assets/icons/Bottom_Menu/home_select.png'),
    IC_BOTTOMMENU_HOMEUNSELECT: require('../assets/icons/Bottom_Menu/home_unselect.png'),
    IC_BOTTOMMENU_WISHLISTSELECT: require('../assets/icons/Bottom_Menu/wishlist_select.png'),
    IC_BOTTOMMENU_WISHLISTUNSELECT:  require('../assets/icons/Bottom_Menu/wishlist_unselect.png'),
    IC_BOTTOMMENU_CARTSELECT:  require('../assets/icons/Bottom_Menu/cart_select.png'),
    IC_BOTTOMMENU_CARTUNSELECT:  require('../assets/icons/Bottom_Menu/plus.png'),
    IC_BOTTOMMENU_SEARCHSELECT:  require('../assets/icons/Bottom_Menu/search_select.png'),
    IC_BOTTOMMENU_SEARCHUNSELECT:  require('../assets/icons/Bottom_Menu/search_unselect.png'),
    IC_BOTTOMMENU_SETTINGSELECT:  require('../assets/icons/Bottom_Menu/settings_active.png'),
    IC_BOTTOMMENU_SETTINGUNSELECT:  require('../assets/icons/Bottom_Menu/settings.png'),
    IC_RIGHT_ARROW: require("../assets/icons/right_arrow.png"),
    IC_CLOCK:require("../assets/icons/clock.png"),
    IC_STAR: require("../assets/icons/star.png"),
    IC_STAR_UNFILLED: require("../assets/icons/star_unfilled.png"),
    IC_CALENDER:require("../assets/icons/calender.png"),
    IC_BACK_ARROW :require('../assets/icons/ic_arrow_back.png'),
    IC_DELETE :require('../assets/icons/delete_icon.png')
  };


  export const image = {
   ONBOARDING1:require('../assets/image/WT1.png'),
   ONBOARDING2:require('../assets/image/WT2.png'),
   ONBOARDING3:require('../assets/image/WT3.png'),
   LOGO1:require('../assets/image/logo.png'),
   LOGO2:require('../assets/image/logo2.png'),
   GETSTART:require('../assets/image/getstart.png'),
   SUCCESSFULL:require('../assets/image/sucessfull.png'),
   PROFILE: require('../assets/image/profile.png'),
   FEATURE1: require('../assets/image/feature1.png'),
   FEATURE2: require('../assets/image/feature2.png'),
   FEATURE3: require('../assets/image/feature3.png'),
   FEATURE4: require('../assets/image/feature4.png'),
   FEATURE5: require('../assets/image/feature5.png'),
   CAROUSALIMG: require('../assets/image/Carousal_img.png'),
   DOD_IMG1:require("../assets/image/DOD/image1.png"),
   DOD_IMG2:require("../assets/image/DOD/image2.png"),
   SPECIAL_OFFER:require("../assets/image/special_offer.png"),
   HEELS:require("../assets/image/heels.png"),
   COMPLETED:require("../assets/image/completed.png"),

  };
